web/router.ex
defmodule CercleApi.Router do
  use CercleApi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :basic_auth do
    plug BasicAuth, use_config: {:cercleApi, :basic_auth}
  end

  pipeline :browser_json do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  pipeline :api_auth do
    plug ExOauth2Provider.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
    plug CercleApi.Plug.CurrentCompany
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :require_login do
    plug Guardian.Plug.EnsureAuthenticated, handler: CercleApi.GuardianErrorHandler
    plug CercleApi.Plug.CurrentUser
    plug CercleApi.Plug.CurrentCompany
  end

  pipeline :already_authenticated do
    plug Guardian.Plug.EnsureNotAuthenticated, handler: CercleApi.GuardianAlreadyAuthenticatedHandler
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth]
    get "/register/:register_values/join/", RegistrationController, :accept_team_invitation
    get "/register/:register_values/join/:useless_gmail", RegistrationController, :accept_team_invitation
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth, :already_authenticated]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
    get "/password/reset/:password_reset_code/confirm", PasswordController, :confirm
    post "/password/reset/:password_reset_code/confirm", PasswordController, :confirm_submit
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth, :require_login]

    get "/logout", SessionController, :delete

  end

  scope "/company/:company_id", CercleApi, as: :front do
    pipe_through [:browser, :browser_auth, :require_login]
    resources "/board", BoardController do
      resources "/card", CardController, only: [:show]
    end
    get "/contact", ContactController, :index
    get "/contact/new", ContactController, :new
    get "/contact/:id", ContactController, :show
    get "/contact/:id/card/:card_id", ContactController, :show

    get "/activity", ActivityController, :index

    get "/import", ImportController, :import
    post "/import_data", ImportController, :import_data
    post "/view_uploaded_data", ImportController, :view_uploaded_data
    post "/create_nested_data", ImportController, :create_nested_data

    get "/settings/profile", Settings.ProfileController, :edit, as: :edit_profile

    scope "/settings", Settings, as: :settings do
      resources "/companies", CompanyController
    end
    get "/settings/team_edit", SettingsController, :team_edit
    get "/settings/fields_edit", SettingsController, :fields_edit
    put "/settings/fields_update", SettingsController, :fields_update
    get "/settings/tags_edit", SettingsController, :tags_edit
    get "/settings/api_key", SettingsController, :api_key

  end

  scope "/api/v2", CercleApi.APIV2 do
    pipe_through [:api, :api_auth]

    post "/register", UserController, :create
    post "/login", SessionController, :create
    resources "/companies", CompanyController

    resources "/profile", UserProfileController, only: [:show, :update], singleton: true
  end

  scope "/api/v2/company/:company_id", CercleApi.APIV2 do
    pipe_through [:api, :api_auth]
    resources "/contact", ContactController

    get "/company/users", CompanyController, :users
    post "/contact/export", ContactExportController, :export
    put "/contact/:id/update_tags", ContactController, :update_tags
    put "/contact/:id/utags", ContactController, :utags
    delete "/contact/multiple/delete", ContactController, :multiple_delete
    get "/settings/api_key", SettingsController, :api_keys

    delete "/settings/team/:id", TeamController, :delete
    post "/settings/team/invitation", TeamController, :invitation

    resources "/organizations", OrganizationController
    resources "/card", CardController do
      resources "/attachments", CardAttachmentController,
        only: [:index, :create, :delete]
    end
    resources "/tag", TagController, only: [:index, :create, :update, :delete]

    resources "/activity", ActivityController
    resources "/board", BoardController do
      put "/archive", BoardController, :archive, as: :archive
      put "/unarchive", BoardController, :unarchive, as: :unarchive
      put "/reorder_columns", BoardController, :reorder_columns
    end
    resources "/board_column", BoardColumnController do
      put "/reorder_cards", BoardColumnController, :reorder_cards
    end
    post "/bulk_contact_create", BulkController, :bulk_contact_create
    post "/bulk_tag_or_untag_contacts", BulkController, :bulk_tag_or_untag_contacts
    get "/user", UserController, :index
    resources "/timeline_events", TimelineEventController

    resources "/email", EmailController
  end

  scope "/admin" , CercleApi.Admin, as: :admin do
    pipe_through :browser # Use the default browser stack
    pipe_through :basic_auth

    resources "/users", UserController
    resources "/companies", CompanyController
    resources "/oauth_application", OauthApplicationController, except: [:show]
    #resources "/company_services", CompanyServiceController
  end

  scope "/oauth", as: "oauth" do
    post "/token", CercleApi.Oauth.TokenController, :create
    post "/revoke", CercleApi.Oauth.TokenController, :revoke
    post "/refresh", CercleApi.Oauth.TokenController, :create
  end

  scope "/oauth", as: "oauth" do
    pipe_through [:browser, :browser_auth, :require_login]
    scope "/authorize" do
      get "/", CercleApi.Oauth.AuthorizationController, :new
      post "/", CercleApi.Oauth.AuthorizationController, :create
      get "/:code", CercleApi.Oauth.AuthorizationController, :show
      delete "/", CercleApi.Oauth.AuthorizationController, :delete
    end
  end

end

web/controllers/password_controller.ex
defmodule CercleApi.PasswordController do
  use CercleApi.Web, :controller

  alias CercleApi.{User, Repo, Mailer}

  def forget_password(conn, _) do
    conn
    |> render(:forget_password)
  end

  def reset_password(conn, %{"user" => %{"email" => email}}) do
    user = Repo.get_by(User, login: email)

    if user do
      length = 40
      random_string = :crypto.strong_rand_bytes(length) |> Base.url_encode64 |> binary_part(0, length)
      changeset = User.changeset(user, %{password_reset_code: random_string})

      case Repo.update(changeset) do
        {:ok, user} ->
          password_reset_mail = %Mailman.Email{
            subject: "Reset password",
            from: "referral@cercle.co",
            to: [user.login],
            html: Phoenix.View.render_to_string(CercleApi.EmailView, "password_reset.html", user: user)
          }
          Mailer.deliver password_reset_mail

          conn
          |> put_flash(:info, "Password reset link has been sent to your email address.")
          |> redirect(to: session_path(conn, :new))
        {:error, _changeset} ->
          conn
          |> put_flash(:error, "Unable to generate password reset code")
          |> redirect(to: "/")
      end
    else
      conn
      |> put_flash(:error, "Invalid email")
      |> redirect(to: "/")
    end
  end

  def confirm(conn, %{"password_reset_code" => password_reset_code}) do
    user = Repo.get_by(User, password_reset_code: password_reset_code)

    if user do
      conn
      |> render("confirm.html", user: user)
    else
      conn
      |> put_flash(:error, "Invalid reset link")
      |> redirect(to: "/")
    end
  end

  def confirm_submit(conn, %{"password_reset_code" => password_reset_code, "user" => %{"password" => password}}) do
    user = Repo.get_by(User, password_reset_code: password_reset_code)

    if user do
      changeset = User.registration_changeset(user, %{password: password, password_reset_code: ""})

      case Repo.update(changeset) do
        {:ok, _user} ->
          conn
          |> put_flash(:info, "Password updated, please login")
          |> redirect(to: session_path(conn, :new))
        {:error, _changeset} ->
          conn
          |> put_flash(:error, "Unable to update password")
          |> redirect(to: "/")
      end
    else
      conn
      |> put_flash(:error, "Invalid reset link")
      |> redirect(to: "/")
    end
  end
end

web/views/password_view.ex
defmodule CercleApi.PasswordView do
  use CercleApi.Web, :view
end

web/templates/password/confirm.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Appcercle | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/adminlte/bootstrap/css/bootstrap.min.css") %>">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/adminlte/dist/css/AdminLTE.min.css") %>">
    <!-- iCheck -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/adminlte/plugins/iCheck/square/blue.css") %>">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <img src="/images/logo_cercle3.png" style="width:106px;">
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Enter new password</p>
        <%= form_for @conn, "/password/reset/#{@user.password_reset_code}/confirm", [as: :user], fn f -> %>
          <div class="form-group">
            <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= password_input f, :password_confirmation, placeholder: "Password confirmation", class: "form-control" %>
          </div>
          <%= submit "Reset Password", class: "btn btn-primary" %>
        <% end %>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
    <!-- jQuery 2.1.4 -->
    <script src="<%= static_path(@conn, "/adminlte/plugins/jQuery/jQuery-2.2.0.min.js") %>"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<%= static_path(@conn, "/adminlte/bootstrap/js/bootstrap.min.js") %>"></script>
  </body>
</html>

web/templates/password/forget_password.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Appcercle | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/adminlte/bootstrap/css/bootstrap.min.css") %>">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/adminlte/dist/css/AdminLTE.min.css") %>">
    <!-- iCheck -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/adminlte/plugins/iCheck/square/blue.css") %>">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">

    <div class="login-box">
      <div class="login-logo">
        <img src="/images/logo_cercle3.png" style="width:106px;">
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Request new password</p>




        <%= form_for @conn, password_path(@conn, :reset_password), [as: :user], fn f -> %>

          <div class="form-group">
            <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
          </div>

          <%= submit "Reset Password", class: "btn btn-primary" %>

        <% end %>





      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->


    <!-- jQuery 2.1.4 -->
    <script src="<%= static_path(@conn, "/adminlte/plugins/jQuery/jQuery-2.2.0.min.js") %>"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<%= static_path(@conn, "/adminlte/bootstrap/js/bootstrap.min.js") %>"></script>
    <!-- iCheck -->
    <script src="<%= static_path(@conn, "/adminlte/plugins/iCheck/icheck.min.js") %>"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>