web/router.ex
defmodule CercleApi.Router do
  use CercleApi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :basic_auth do
    plug BasicAuth, use_config: {:cercleApi, :basic_auth}
  end

  pipeline :browser_json do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  pipeline :api_auth do
    plug ExOauth2Provider.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
    plug CercleApi.Plug.CurrentCompany
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :require_login do
    plug Guardian.Plug.EnsureAuthenticated, handler: CercleApi.GuardianErrorHandler
    plug CercleApi.Plug.CurrentUser
    plug CercleApi.Plug.CurrentCompany
  end

  pipeline :already_authenticated do
    plug Guardian.Plug.EnsureNotAuthenticated, handler: CercleApi.GuardianAlreadyAuthenticatedHandler
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth]
    get "/register/:register_values/join/", RegistrationController, :accept_team_invitation
    get "/register/:register_values/join/:useless_gmail", RegistrationController, :accept_team_invitation
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth, :already_authenticated]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
    get "/password/reset/:password_reset_code/confirm", PasswordController, :confirm
    post "/password/reset/:password_reset_code/confirm", PasswordController, :confirm_submit
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth, :require_login]

    get "/logout", SessionController, :delete

  end

  scope "/company/:company_id", CercleApi, as: :front do
    pipe_through [:browser, :browser_auth, :require_login]
    resources "/board", BoardController do
      resources "/card", CardController, only: [:show]
    end
    get "/contact", ContactController, :index
    get "/contact/new", ContactController, :new
    get "/contact/:id", ContactController, :show
    get "/contact/:id/card/:card_id", ContactController, :show

    get "/activity", ActivityController, :index

    get "/import", ImportController, :import
    post "/import_data", ImportController, :import_data
    post "/view_uploaded_data", ImportController, :view_uploaded_data
    post "/create_nested_data", ImportController, :create_nested_data

    get "/settings/profile", Settings.ProfileController, :edit, as: :edit_profile

    scope "/settings", Settings, as: :settings do
      resources "/companies", CompanyController
    end
    get "/settings/team_edit", SettingsController, :team_edit
    get "/settings/fields_edit", SettingsController, :fields_edit
    put "/settings/fields_update", SettingsController, :fields_update
    get "/settings/tags_edit", SettingsController, :tags_edit
    get "/settings/api_key", SettingsController, :api_key

  end

  scope "/api/v2", CercleApi.APIV2 do
    pipe_through [:api, :api_auth]

    post "/register", UserController, :create
    post "/login", SessionController, :create
    resources "/companies", CompanyController

    resources "/profile", UserProfileController, only: [:show, :update], singleton: true
  end

  scope "/api/v2/company/:company_id", CercleApi.APIV2 do
    pipe_through [:api, :api_auth]
    resources "/contact", ContactController

    get "/company/users", CompanyController, :users
    post "/contact/export", ContactExportController, :export
    put "/contact/:id/update_tags", ContactController, :update_tags
    put "/contact/:id/utags", ContactController, :utags
    delete "/contact/multiple/delete", ContactController, :multiple_delete
    get "/settings/api_key", SettingsController, :api_keys

    delete "/settings/team/:id", TeamController, :delete
    post "/settings/team/invitation", TeamController, :invitation

    resources "/organizations", OrganizationController
    resources "/card", CardController do
      resources "/attachments", CardAttachmentController,
        only: [:index, :create, :delete]
    end
    resources "/tag", TagController, only: [:index, :create, :update, :delete]

    resources "/activity", ActivityController
    resources "/board", BoardController do
      put "/archive", BoardController, :archive, as: :archive
      put "/unarchive", BoardController, :unarchive, as: :unarchive
      put "/reorder_columns", BoardController, :reorder_columns
    end
    resources "/board_column", BoardColumnController do
      put "/reorder_cards", BoardColumnController, :reorder_cards
    end
    post "/bulk_contact_create", BulkController, :bulk_contact_create
    post "/bulk_tag_or_untag_contacts", BulkController, :bulk_tag_or_untag_contacts
    get "/user", UserController, :index
    resources "/timeline_events", TimelineEventController

    resources "/email", EmailController
  end

  scope "/admin" , CercleApi.Admin, as: :admin do
    pipe_through :browser # Use the default browser stack
    pipe_through :basic_auth

    resources "/users", UserController
    resources "/companies", CompanyController
    resources "/oauth_application", OauthApplicationController, except: [:show]
    #resources "/company_services", CompanyServiceController
  end

  scope "/oauth", as: "oauth" do
    post "/token", CercleApi.Oauth.TokenController, :create
    post "/revoke", CercleApi.Oauth.TokenController, :revoke
    post "/refresh", CercleApi.Oauth.TokenController, :create
  end

  scope "/oauth", as: "oauth" do
    pipe_through [:browser, :browser_auth, :require_login]
    scope "/authorize" do
      get "/", CercleApi.Oauth.AuthorizationController, :new
      post "/", CercleApi.Oauth.AuthorizationController, :create
      get "/:code", CercleApi.Oauth.AuthorizationController, :show
      delete "/", CercleApi.Oauth.AuthorizationController, :delete
    end
  end

end

web/controllers/import_controller.ex
defmodule CercleApi.ImportController do
  @moduledoc """
  upload and parse import contact file.
  """

  use CercleApi.Web, :controller
  use Timex

  alias CercleApi.{Company, Tag, Card, ImportContactFile}

  require Logger

  def import(conn, _params) do
    conn
      |> put_layout("adminlte.html")
      |> render("import.html")
  end

  def import_data(conn, %{"file" => upload_file}) do
    file_type = upload_file.content_type
    items = ImportContactFile.parse(upload_file, file_type)

    changeset = %ImportContactFile{}
    |> ImportContactFile.changeset(
      %{"content" => %{items: items}, "content_type" => file_type}
    )

    case Repo.insert(changeset) do
      {:ok, import_file} ->
        render(conn, "mapping.json", table: items, uuid: import_file.uuid)
      {:error, :changeset} ->
        json conn, %{error_message: "Maximum 10,000 records are permitted"}
    end

  end

  def view_uploaded_data(conn, %{"mapping" => mapping, "temp_file" => uuid}) do
    import_file = Repo.get_by!(ImportContactFile, uuid: uuid)
    table = import_file.content["items"]
    render(conn, "preview_data.json",
      mapping: mapping, table: table, uuid: uuid
    )
  end

  def create_nested_data(conn, %{"mapping" => mapping, "temp_file" => temp_file}) do
    user = Guardian.Plug.current_resource(conn)
    company = current_company(conn)
    import_file = Repo.get_by!(ImportContactFile, uuid: temp_file)
    [_|rows] = import_file.content["items"]
    header = ImportContactFile.header(import_file)
    total_rows = Enum.count(rows) - 1
    iterations = div(total_rows, 100)
    str_tag_id = imported_tag_id(user, company.id)
    responses  = for n <- 0..iterations do
      lower..upper = (n * 100..(n + 1) * 100 -1)
      if upper > total_rows do
        upper = total_rows - 1
      end

      items = for i <- lower..upper do
        row_data = %{}
        row = prepare_row(rows, i, header)
        contact_data = contact_data_mapping(row, mapping["contact"])
        organization_data = organization_data_mapping(row, mapping["organization"])

        Map.put(row_data, "contact", contact_data)
        |> Map.put("organization", organization_data)
      end

      contacts = CercleApi.APIV2.BulkController.bulk_contact_create(
        conn, %{"items" => items, "return" => true}
      )
      CercleApi.APIV2.BulkController.bulk_tag_or_untag_contacts(conn,
        %{
          "contacts" => contacts, "tag_id" => str_tag_id,
          "untag" => false, "return" => true
        })
    end

    Repo.delete!(import_file)
    json conn, %{status: "200", message: "Records imported successfully"}
  end

  defp contact_data_mapping(row, mapping) do
    %{
      "first_name" => row[mapping["first_name"]],
      "last_name" => row[mapping["last_name"]],
      "full_name" => row[mapping["full_name"]],
      "email" => row[mapping["email"]],
      "phone" => row[mapping["phone"]],
      "description" => row[mapping["description"]],
      "job_title" => row[mapping["job_title"]]
    }
  end

  defp organization_data_mapping(row, mapping) do
    %{
      "name" => row[mapping["name"]],
      "website" => row[mapping["website"]],
      "description" => row[mapping["description"]]
    }
  end

  defp imported_tag_id(user, company_id) do
    datetime = Timezone.convert(Timex.now, user.time_zone)
    date = Timex.format!(datetime, "%m/%d/%Y", :strftime)
    time = Timex.format!(datetime, "%H:%M", :strftime)
    tag_name = "imported #{date} at #{time}"
    tag = %Tag{name: tag_name, company_id: company_id}
    |> Repo.insert!
    Integer.to_string(tag.id)
  end

  defp prepare_row(rows, index, header) do
    row = Enum.at(rows, index)
    |> Enum.map(&String.strip(&1))
    Enum.zip(header, row)
    |> Enum.into(%{})
  end
end

web/views/import_view.ex
defmodule CercleApi.ImportView do
  use CercleApi.Web, :view

  @contact_fields ["first_name", "last_name", "full_name",
                   "email", "description", "phone", "job_title"]
  @organization_fields ["name", "website", "description"]

  def render("mapping.json", %{table: table, uuid: uuid}) do
    [headers|rows]= table
    first_row = Enum.at(rows, 0)
    top_five_rows = Enum.take(rows, 5)

    %{
      headers: headers,
      first_row: first_row,
      top_five_rows: top_five_rows,
      contact_fields: @contact_fields,
      organization_fields: @organization_fields,
      temp_file: uuid
    }
  end

  def render("preview_data.json", %{mapping: mapping, table: table, uuid: uuid}) do
    total_rows = Enum.count(table) - 1
    contact_headers = Map.keys(mapping["contact"])
    organization_headers = Map.keys(mapping["organization"])
    header = Enum.map(Enum.at(table, 0), &String.strip(&1))
    first_row = Enum.zip(header, Enum.at(table, 1)) |> Enum.into(%{})
    contact_values = for {db_col, csv_col} <- mapping["contact"] do
      first_row[csv_col]
    end
    organization_values = for {db_col, csv_col} <- mapping["organization"] do
      first_row[csv_col]
    end

    %{
      contact_headers: contact_headers,
      organization_headers: organization_headers,
      contact_values: contact_values,
      organization_values: organization_values,
      temp_file: uuid
    }
  end
end

web/templates/import/import.html.eex
<div class="import-parent-div">
	<h2>Import data</h2>
	<div>
		<ul class="steps-ul">
			<li class="steps-li active steps-li-active" id="step1"><b>Step 1:</b> Upload file
	      <span class="arrow">
	      </span>
      </li>
			<li class="steps-li steps-li-inactive" id="step2"><b>Step 2:</b> Mapping
	      <span class="arrow">
	      </span>
      </li>
			<li class="steps-li steps-li-inactive" id="step3"><b>Step 3:</b> Preview and finish
	      <span class="">
	      </span>
      </li>
		</ul>
	</div>
</div>
<div class="upload-outer-box" id="sec-1">
	<div class="upload-dashed-box">
		<div class="upload-info-box">
		  <form id="fileupload" action="<%=front_import_path(@conn, :import_data, @conn.assigns[:current_company].id)%>" method="POST" enctype="multipart/form-data">
		    <div class="row fileupload-buttonbar">
		      <div class="col-md-12">
		        <span class="btn btn-success fileinput-button">
		          <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
		          <span>Upload file</span>
		          <input type="file" name="file" id="fileupload">
		        </span>
		        &nbsp;&nbsp;
		        <span><b>...or drag a file here.</b></span>
		        <span class="fileupload-process"></span>
		      </div>
		      <br><br><br>
		      <div class="col-md-12">Only Excel (.xls and .xlsx) and .csv file types are supported.
		      </div>
		    </div>
		  </form>
		</div>
	</div>
	<div class="table-responsive hidden" id="list-uploaded-file">
		<table class="table table-bordered">
			<thead>
				<tr class="tb-head">
					<th>File Name</th>
					<th>File Size</th>
					<th>File Type</th>
					<th>Last Modified</th>
				</tr>
			</thead>
			<tbody>
				<tr class="success">
				  <td></td><td></td><td></td><td></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="progress-section">
		<p id="uploaded-file-name"></p>
		<div class="progress" id="progress">
		  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
		  </div>
		</div>
	</div>
</div>
<div id="action-btns-step1">
	<%=link "Next", to: "" , class: "btn btn-success pull-right disabled", id: "move-to-step2", style: "margin-left:5px"%>
	<%=link "Cancel Import", to: front_contact_path(@conn, :index, @conn.assigns[:current_company].id), class: "cancel-import btn btn-danger pull-right"%>
</div>
<div class="upload-outer-box hidden" id="sec-2">
	<div class="mapping-info">
		<h4><i>Drag fields from the right side picker to the left side boxes matching your data. Unmapped columns will not be imported into Cercle.</i></h4>
	</div>
	<div class="row mapping-sections">
		<div class="col-md-8" id="left-section">
			<i class="fa fa-file fa-lg" aria-hidden="true"></i> &nbsp; File Fields
			<div class="table-responsive">
				<table class="table table-bordered" id="left-section-table">
					<tbody></tbody>
				</table>
			</div>
		</div>
		<div class="col-md-4" id="right-section">
			<ul class="nav nav-tabs" id="myTabs" role="tablist">
			  <li role="presentation" class="active">
			  	<a href="#contact" id="contact-tab" role="tab" data-toggle="tab" aria-controls="contact" aria-expanded="true"><i class="fa fa-user fa-lg" aria-hidden="true"></i> &nbsp; Contact Fields</a>
			  </li>
			  <li role="presentation">
			  	<a href="#organization" id="organization-tab" role="tab" data-toggle="tab" aria-controls="organization" aria-expanded="true"><i class="fa fa-building fa-lg" aria-hidden="true"></i> &nbsp; Organization Fields</a>
			  </li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade active in" role="tabpanel" id="contact" aria-labelledby="contact-tab">
					<div class="table-responsive">
						<table class="table table-bordered" id="contact-field-table">
							<tbody></tbody>
						</table>
					</div>
				</div>
				<div class="tab-pane fade" role="tabpanel" id="organization" aria-labelledby="organization-tab">
					<div class="table-responsive">
						<table class="table table-bordered" id="organization-field-table">
							<tbody></tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="action-btns-step2" class="hidden">
	<%=link "Back", to: "#" , id: "back-to-step1", class: "btn btn-default pull-left", style: "margin-left:5px"%>
	<%=link "Next", to: "#" , class: "btn btn-success pull-right disabled", id: "move-to-step3",  style: "margin-left:5px"%>
	<%=link "Cancel Import", to: "", class: "cancel-import btn btn-danger pull-right"%>
</div>
<div class="upload-outer-box hidden" id="sec-3">
	<div class="preview-info-section">
		<h3>Preview Data</h3>
		<p>Have a preview data according to the mapping done in <b>Step 2</b></p>
	</div>
	<div class="preview-section">
		<div class="table-responsive">
			<table class="table table-bordered" id="preview-data-table">
				<caption class="table-caption"></caption>
				<thead id="preview-head"></thead>
				<tbody id="preview-body"></tbody>
			</table>
		</div>
		<div class="progress-section">
			<div class="progress" id="final-progress">
				<div class="progress-bar progress-bar-success progress-bar-striped active hidden" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
			  </div>
		  </div>
	  </div>
	</div>
</div>
<div id="action-btns-step3" class="hidden">
	<%=link "Back", to: "#" , id: "back-to-step2", class: "btn btn-default pull-left", style: "margin-left:5px"%>
	<%=link "Finish", to: "#" , class: "btn btn-success pull-right", id: "move-to-final",  style: "margin-left:5px"%>
	<%=link "Cancel Import", to: "", class: "cancel-import btn btn-danger pull-right"%>
</div>
<script type="text/javascript">

  var uploadType;
  var contact = {};
  var organization ={};
  var jsonData = {};
  var companyId = <%=@conn.assigns[:current_company].id%>;

  function allowDrop(ev) {
  ev.preventDefault();
  }

  function drag(ev) {
  ev.dataTransfer.setData('text/plain', ev.target.id);
  uploadType = $('#'+ev.target.id).closest('div').parent().attr('id');
  }

  function drop(ev) {
  var data = ev.dataTransfer.getData('text/plain');
  ev.target.innerHTML = document.getElementById(data).innerHTML + '<i class="revert fa fa-times" aria-hidden="true" style="float:right; margin-top:2px; cursor: pointer;"></i>';
  ev.target.className = ('contact-fields active');
  var dbCol = $('#'+data).find('.db-field').text();
  var csvCol = $('#'+ev.target.id).prev('td').find('.csv-col').text();
  if(uploadType == 'contact'){
  contact[dbCol] = csvCol;
  }
  else{
  organization[dbCol] = csvCol;
  }
  jsonData['contact'] = contact;
  jsonData['organization'] = organization;
  $('#move-to-step3').removeClass('disabled');
  }

</script>