web/router.ex
defmodule CercleApi.Router do
  use CercleApi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :basic_auth do
    plug BasicAuth, use_config: {:cercleApi, :basic_auth}
  end

  pipeline :browser_json do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  pipeline :api_auth do
    plug ExOauth2Provider.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
    plug CercleApi.Plug.CurrentCompany
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :require_login do
    plug Guardian.Plug.EnsureAuthenticated, handler: CercleApi.GuardianErrorHandler
    plug CercleApi.Plug.CurrentUser
    plug CercleApi.Plug.CurrentCompany
  end

  pipeline :already_authenticated do
    plug Guardian.Plug.EnsureNotAuthenticated, handler: CercleApi.GuardianAlreadyAuthenticatedHandler
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth]
    get "/register/:register_values/join/", RegistrationController, :accept_team_invitation
    get "/register/:register_values/join/:useless_gmail", RegistrationController, :accept_team_invitation
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth, :already_authenticated]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
    get "/password/reset/:password_reset_code/confirm", PasswordController, :confirm
    post "/password/reset/:password_reset_code/confirm", PasswordController, :confirm_submit
  end

  scope "/", CercleApi do
    pipe_through [:browser, :browser_auth, :require_login]

    get "/logout", SessionController, :delete

  end

  scope "/company/:company_id", CercleApi, as: :front do
    pipe_through [:browser, :browser_auth, :require_login]
    resources "/board", BoardController do
      resources "/card", CardController, only: [:show]
    end
    get "/contact", ContactController, :index
    get "/contact/new", ContactController, :new
    get "/contact/:id", ContactController, :show
    get "/contact/:id/card/:card_id", ContactController, :show

    get "/activity", ActivityController, :index

    get "/import", ImportController, :import
    post "/import_data", ImportController, :import_data
    post "/view_uploaded_data", ImportController, :view_uploaded_data
    post "/create_nested_data", ImportController, :create_nested_data

    get "/settings/profile", Settings.ProfileController, :edit, as: :edit_profile

    scope "/settings", Settings, as: :settings do
      resources "/companies", CompanyController
    end
    get "/settings/team_edit", SettingsController, :team_edit
    get "/settings/fields_edit", SettingsController, :fields_edit
    put "/settings/fields_update", SettingsController, :fields_update
    get "/settings/tags_edit", SettingsController, :tags_edit
    get "/settings/api_key", SettingsController, :api_key

  end

  scope "/api/v2", CercleApi.APIV2 do
    pipe_through [:api, :api_auth]

    post "/register", UserController, :create
    post "/login", SessionController, :create
    resources "/companies", CompanyController

    resources "/profile", UserProfileController, only: [:show, :update], singleton: true
  end

  scope "/api/v2/company/:company_id", CercleApi.APIV2 do
    pipe_through [:api, :api_auth]
    resources "/contact", ContactController

    get "/company/users", CompanyController, :users
    post "/contact/export", ContactExportController, :export
    put "/contact/:id/update_tags", ContactController, :update_tags
    put "/contact/:id/utags", ContactController, :utags
    delete "/contact/multiple/delete", ContactController, :multiple_delete
    get "/settings/api_key", SettingsController, :api_keys

    delete "/settings/team/:id", TeamController, :delete
    post "/settings/team/invitation", TeamController, :invitation

    resources "/organizations", OrganizationController
    resources "/card", CardController do
      resources "/attachments", CardAttachmentController,
        only: [:index, :create, :delete]
    end
    resources "/tag", TagController, only: [:index, :create, :update, :delete]

    resources "/activity", ActivityController
    resources "/board", BoardController do
      put "/archive", BoardController, :archive, as: :archive
      put "/unarchive", BoardController, :unarchive, as: :unarchive
      put "/reorder_columns", BoardController, :reorder_columns
    end
    resources "/board_column", BoardColumnController do
      put "/reorder_cards", BoardColumnController, :reorder_cards
    end
    post "/bulk_contact_create", BulkController, :bulk_contact_create
    post "/bulk_tag_or_untag_contacts", BulkController, :bulk_tag_or_untag_contacts
    get "/user", UserController, :index
    resources "/timeline_events", TimelineEventController

    resources "/email", EmailController
  end

  scope "/admin" , CercleApi.Admin, as: :admin do
    pipe_through :browser # Use the default browser stack
    pipe_through :basic_auth

    resources "/users", UserController
    resources "/companies", CompanyController
    resources "/oauth_application", OauthApplicationController, except: [:show]
    #resources "/company_services", CompanyServiceController
  end

  scope "/oauth", as: "oauth" do
    post "/token", CercleApi.Oauth.TokenController, :create
    post "/revoke", CercleApi.Oauth.TokenController, :revoke
    post "/refresh", CercleApi.Oauth.TokenController, :create
  end

  scope "/oauth", as: "oauth" do
    pipe_through [:browser, :browser_auth, :require_login]
    scope "/authorize" do
      get "/", CercleApi.Oauth.AuthorizationController, :new
      post "/", CercleApi.Oauth.AuthorizationController, :create
      get "/:code", CercleApi.Oauth.AuthorizationController, :show
      delete "/", CercleApi.Oauth.AuthorizationController, :delete
    end
  end

end

web/views/shared_view.ex
defmodule CercleApi.SharedView do
  use CercleApi.Web, :view
end

web/templates/shared/flashes.html.eex
<%= if get_flash(@conn, :info) do %>
<p class="alert alert-info" role="alert" style="border-radius:0px;"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :success) do %>
<p class="alert alert-success" role="alert" style="border-radius:0px;"><%= get_flash(@conn, :success) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
<p class="alert alert-danger" role="alert" style="border-radius:0px;"><%= get_flash(@conn, :error) %></p>
<% end %>

web/templates/shared/navbar.html.eex
<nav class="navbar navbar-static-top" style="background-color:black;">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">
        <img src="/images/logo_cercle2.png" style="width:56px;position:relative;top:-14px;left:10px;">
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <i class="fa fa-bars"></i>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">

      <ul class="nav navbar-nav">
        <%= if @conn.assigns[:current_company] do %>
        <li>
          <router-link to="/company/<%= @conn.assigns[:current_company].id %>/activity">
            <!--
                <span class="label label-primary">4</span>
                -->
            Inbox
          </router-link>
        </li>
        <li><router-link to="/company/<%= @conn.assigns[:current_company].id %>/board">Boards</a></router-link>
        <li>
          <router-link to="/company/<%= @conn.assigns[:current_company].id %>/contact">People</router-link>
        </li>
        <%end%>
      </ul>

    </div><!-- /.navbar-collapse -->

    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu" id="user-navbar">
      <navbar
        :user="<%= Poison.encode! @conn.assigns[:current_user] %>"
        :company="<%= Poison.encode! @conn.assigns[:current_company] %>"
        :companies="<%= Poison.encode!(CercleApi.Company.user_companies(@conn.assigns[:current_user])) %>"
        />
    </div><!-- /.navbar-custom-menu -->
  </div><!-- /.container-fluid -->
</nav>

web/templates/shared/settings_nav.html.eex
<ul class="nav nav-pills nav-stacked">

  <li class="<%= assigns[:active] && (@active == :profile) && "active" %>">
    <a href="<%= front_edit_profile_path(@conn, :edit, @conn.assigns[:current_company].id) %>">
      <i class="fa fa-edit"></i>
      Profile
    </a>
  </li>

  <li class="<%= assigns[:active] && (@active == :company) && "active" %>">
    <a href="<%= front_settings_company_path(@conn, :index, @conn.assigns[:current_company].id) %>">
      <i class="fa fa-edit"></i>
      Companies
    </a>
  </li>
  <li class="<%= assigns[:active] && (@active == :team) && "active" %>">
    <a href="<%= front_settings_path(@conn, :team_edit, @conn.assigns[:current_company].id)%>"><i class="fa fa-edit"></i>Team</a>
  </li>

  <li class="<%= assigns[:active] && (@active == :integration) && "active" %>">
    <a href="/company/<%= @conn.assigns[:current_company].id %>/settings/api_key">
      <i class="fa fa-edit"></i>
      Integration
    </a>
  </li>
  <li>
    <a href="/company/<%= @conn.assigns[:current_company].id %>/import">
      <i class="fa fa-edit"></i>Import
    </a>
  </li>
</ul>